"""Preprocessing utilities for labor market vacancy datasets."""

from .aggregation import (
    DEFAULT_MONTHLY_GROUP_COLUMNS,
    MONTHLY_SEGMENT_COLUMNS,
    SegmentAggregator,
)
from .canonical import (
    CANONICAL_VACANCY_COLUMNS,
    REQUIRED_CANONICAL_COLUMNS,
    CanonicalTransformer,
)
from .constants import (
    DATA_DIR,
    PROCESSED_DATA_DIR,
    PROJECT_ROOT,
    RAW_DATA_DIR,
    RAW_DATASET_PATHS,
    SOURCE_COMBINED,
    SOURCE_DATASET_LABELS,
    SOURCE_HH_GITHUB,
    SOURCE_HH_KAGGLE,
    SOURCE_TRUDVSEM_LATEST,
    SUPPORTED_SOURCE_DATASETS,
    SourceDataset,
    validate_source_dataset,
)
from .dates import DateProcessor
from .io import DatasetReader, DataProfiler, profile_raw_datasets
from .merge import (
    BUILD_MODE_SOURCES,
    BuildMode,
    CanonicalSourceMerger,
    MergeResult,
    merge_canonical_sources,
)
from .ml import (
    BROAD_MONTHLY_CATEGORICAL_FEATURES,
    BROAD_MONTHLY_DYNAMIC_FEATURES,
    BROAD_MONTHLY_LAG_FEATURES,
    BROAD_MONTHLY_NUMERIC_FEATURES,
    BROAD_MONTHLY_OCCUPATION_RARE_THRESHOLD,
    BROAD_MONTHLY_REGION_RARE_THRESHOLD,
    BROAD_MONTHLY_SEGMENT_KEY_COLUMNS,
    BROAD_MONTHLY_SUPPORT_FEATURES,
    BROAD_MONTHLY_TARGET_EXCLUDE_COLUMNS,
    BROAD_MONTHLY_TARGET_COLUMN,
    BROAD_QUARTERLY_CATEGORICAL_FEATURES,
    BROAD_QUARTERLY_DYNAMIC_FEATURES,
    BROAD_QUARTERLY_LAG_FEATURES,
    BROAD_QUARTERLY_NUMERIC_FEATURES,
    BROAD_QUARTERLY_RESIDUAL_TARGET_COLUMN,
    BROAD_QUARTERLY_SEGMENT_KEY_COLUMNS,
    BROAD_QUARTERLY_TARGET_COLUMN,
    GAP_TO_TARGET_MONTHS_COLUMN,
    GAP_TO_TARGET_QUARTERS_COLUMN,
    LAG_FEATURES,
    MLReadinessResult,
    ML_SEGMENT_KEY_COLUMNS,
    BroadMonthlySalaryMLDatasetBuilder,
    BroadMonthlyModelingSetup,
    BroadQuarterlyModelingSetup,
    BroadQuarterlySalaryMLDatasetBuilder,
    MonthlyMLDatasetResult,
    MonthlyMLReadinessAuditor,
    MonthlySalaryMLDatasetBuilder,
    QUARTERLY_LAG_FEATURES,
    QUARTERLY_TARGET_COLUMN,
    QuarterlyMLDatasetResult,
    QuarterlySalaryMLDatasetBuilder,
    TARGET_COLUMN,
    TARGET_MONTH_COLUMN,
    TARGET_QUARTER_COLUMN,
)
from .normalization import Normalizer
from .pipeline import SourcePipelineResult, SourcePreprocessingPipeline, process_source_dataset
from .quality import QualityChecker
from .salary import SalaryProcessor
from .validation import ResultValidator, ValidationResult

__all__ = [
    "CanonicalTransformer",
    "BROAD_MONTHLY_CATEGORICAL_FEATURES",
    "BROAD_MONTHLY_DYNAMIC_FEATURES",
    "BROAD_MONTHLY_LAG_FEATURES",
    "BROAD_MONTHLY_NUMERIC_FEATURES",
    "BROAD_MONTHLY_OCCUPATION_RARE_THRESHOLD",
    "BROAD_MONTHLY_REGION_RARE_THRESHOLD",
    "BROAD_MONTHLY_SEGMENT_KEY_COLUMNS",
    "BROAD_MONTHLY_SUPPORT_FEATURES",
    "BROAD_MONTHLY_TARGET_EXCLUDE_COLUMNS",
    "BROAD_MONTHLY_TARGET_COLUMN",
    "BROAD_QUARTERLY_CATEGORICAL_FEATURES",
    "BROAD_QUARTERLY_DYNAMIC_FEATURES",
    "BROAD_QUARTERLY_LAG_FEATURES",
    "BROAD_QUARTERLY_NUMERIC_FEATURES",
    "BROAD_QUARTERLY_RESIDUAL_TARGET_COLUMN",
    "BROAD_QUARTERLY_SEGMENT_KEY_COLUMNS",
    "BROAD_QUARTERLY_TARGET_COLUMN",
    "BUILD_MODE_SOURCES",
    "CANONICAL_VACANCY_COLUMNS",
    "BroadMonthlyModelingSetup",
    "BroadMonthlySalaryMLDatasetBuilder",
    "BroadQuarterlyModelingSetup",
    "BroadQuarterlySalaryMLDatasetBuilder",
    "BuildMode",
    "CanonicalSourceMerger",
    "DATA_DIR",
    "DataProfiler",
    "DatasetReader",
    "DateProcessor",
    "DEFAULT_MONTHLY_GROUP_COLUMNS",
    "GAP_TO_TARGET_MONTHS_COLUMN",
    "GAP_TO_TARGET_QUARTERS_COLUMN",
    "MergeResult",
    "MLReadinessResult",
    "ML_SEGMENT_KEY_COLUMNS",
    "MonthlyMLDatasetResult",
    "MONTHLY_SEGMENT_COLUMNS",
    "MonthlyMLReadinessAuditor",
    "MonthlySalaryMLDatasetBuilder",
    "QUARTERLY_LAG_FEATURES",
    "QUARTERLY_TARGET_COLUMN",
    "QuarterlyMLDatasetResult",
    "QuarterlySalaryMLDatasetBuilder",
    "LAG_FEATURES",
    "Normalizer",
    "PROCESSED_DATA_DIR",
    "PROJECT_ROOT",
    "QualityChecker",
    "RAW_DATASET_PATHS",
    "RAW_DATA_DIR",
    "REQUIRED_CANONICAL_COLUMNS",
    "SOURCE_COMBINED",
    "SOURCE_DATASET_LABELS",
    "SOURCE_HH_GITHUB",
    "SOURCE_HH_KAGGLE",
    "SOURCE_TRUDVSEM_LATEST",
    "SUPPORTED_SOURCE_DATASETS",
    "SalaryProcessor",
    "SegmentAggregator",
    "TARGET_COLUMN",
    "TARGET_MONTH_COLUMN",
    "TARGET_QUARTER_COLUMN",
    "ResultValidator",
    "SourceDataset",
    "SourcePipelineResult",
    "SourcePreprocessingPipeline",
    "ValidationResult",
    "process_source_dataset",
    "profile_raw_datasets",
    "merge_canonical_sources",
    "validate_source_dataset",
]
